import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Head from "./components/Head";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Mantech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Head/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
